### ISSUE TITLE
feat: please add an option to enable/disable foreground notification

### ISSUE THREAD

**Issue by uppified** [thorito/custom_activity_recognition#1] opened 2024-12-17 11:28 UTC
**Description**

Clearly describe what you are looking to add. The more context the better.

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by thorito** [comment] 2024-12-23 17:50
Closes #1 as duplicate of #2. Closes #1

**Closed as completed by thorito** 2024-12-23 17:50 UTC
